server:
  port: 8082

spring:
  application:
    name: uims-tools

logging:
  config: classpath:spring-logback.xml

report:
  pool:
    corePoolSize: 5
    maxPoolSize: 15
    keepAliveSeconds: 60
    queueCapacity: 50